name: Pending Discussion
run-name: ${{ github.actor }} - pending discussion
on:
  workflow_call:
    secrets:
      ADD_TO_PROJECT_PAT:
        required: true
      GITHUB_TOKEN:
        required: true
jobs:
  run:
    if: github.actor != github.event.issue.user.login && !contains(github.event.issue.labels.*.name, 'pending discussion')
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: "pending discussion"
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/jtorleon-studios-team/projects/4
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
        id: add-project
      - uses: titoportas/update-project-fields@v0.1.0
        with:
          project-url: https://github.com/orgs/jtorleon-studios-team/projects/4
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          item-id: ${{ steps.add-project.outputs.itemId }}
          field-keys: Status
          field-values: Pending Discussion
